# This is the complete and correct configuration for a high-performance static site
# on Cloudflare Workers, using the modern `[assets]` binding.

name = "divortio-pooh-errors"
main = "./src/worker.mjs"

compatibility_date = "2025-08-15"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

minify = true
workers_dev = false
preview_urls = false

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./public"
binding = "ASSETS"


[[routes]]
pattern = "poohErrors.divort.io"
custom_domain = true
